name: Build and Deploy to GKE

on:
  push:
    branches:
      - "**"

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: algo-trial-cluster
  GKE_ZONE: us-central1
  ARTIFACT_REPO: algo-trial
  BACKEND_URL: http://34.170.186.166:8080/v1/
  DEPLOYMENT_NAME: frontend
  IMAGE: algo-trial-frontend-test

jobs:
  Build-Push-Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Auth Google Cloud
        uses: google-github-actions/auth@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
          credentials_json: ${{ secrets.GKE_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker
        run: gcloud --quiet auth configure-docker

      - name: Get GKE Credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}

      - name: Build Docker Image
        run: docker build --platform linux/amd64 \
          --tag "$GKE_ZONE-docker.pkg.dev/$PROJECT_ID/$ARTIFACT_REPO/$IMAGE:$GITHUB_SHA" \
          --build-arg NEXT_PUBLIC_API_URL="${{ env.BACKEND_URL }}" .

      - name: Push Docker Image To Google Artifact Registry
        run: docker push "$GKE_ZONE-docker.pkg.dev/$PROJECT_ID/$ARTIFACT_REPO/$IMAGE:$GITHUB_SHA"

      - name: Deploy to GKE
        run: |
          kubectl set image deployment/$DEPLOYMENT_NAME \
            frontend=$GKE_ZONE-docker.pkg.dev/$PROJECT_ID/$ARTIFACT_REPO/$IMAGE:$GITHUB_SHA
          kubectl rollout status deployment/$DEPLOYMENT_NAME
          kubectl get services -o wide
