name: Build and Push Docker Image

on:
  workflow_run:
    workflows: ["Integration Test"]
    types:
      - completed

env:
  NEXT_PUBLIC_API_URL: http://localhost:8080/v1/

jobs:
  Build-and-Push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to Private Docker Registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t algo-trial-frontend --build-arg NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL .

      - name: Tag Latest and Push
        run: |
          docker tag algo-trial-frontend minhieuchu/algo-trial:frontend
          docker push minhieuchu/algo-trial:frontend
