name: Integration Test
run-name: Running Integration tests for Backtest Form

on: [push]

jobs:
  Run-Integration-Tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - run: mkdir src/pages

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          component: true
